name: Build, Scan, and potentially Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build container image
        run: docker build -t cloud-sec-demo:latest .

      - name: Vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'cloud-sec-demo:latest'
